spring.application.name=hotel

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_reservation_db
spring.datasource.username=root
spring.datasource.password=2106
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Admin Security
app.admin-key=1234
app.admin-username=admin

# PayHere Configuration
payhere.merchant-id=1238301
payhere.merchant-secret=MjgzMzc4MDcxODE5MjY1OTY5NTYxMDA2MTU2ODI3NDE3MzM2NDc1MQ==
payhere.checkout-url=https://sandbox.payhere.lk/pay/checkout

# Application Base URL
app.base-url=https://visibly-gap-goatskin.ngrok-free.dev

# Mail Configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=ba2e5f673889ad
spring.mail.password=4deddd342ae5b4
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
